"""全楽器・声のソース配列からMSZIP埋め込みデータと参照ヘッダーを生成する"""
import argparse
from pathlib import Path
import re

from CompareAudioCompression import windows_codec

ROOT = Path(__file__).resolve().parents[1]
ARRAY = r"inline constexpr std::uint8_t\s+(\w+)\[\]\s*=\s*\{(.*?)\};"


def main():
    """@brief 全音源を保持して生成物を更新または一致検証する
    @return なし
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    header = ["#pragma once", "#include <cstddef>", "#include <cstdint>",
              "// Generated by Scripts/PackAudioSamples.py",
              "namespace Audio::PackedAudioSamples {",
              "struct Entry { std::size_t offset; std::size_t size; };",
              "/** @brief 圧縮音源を一度だけ復元して参照する",
              " * @param offset 全音源バッファ内の位置",
              " * @param size 参照するバイト数",
              " * @return 復元データ、失敗または範囲外の場合nullptr */",
              "const std::uint8_t* Get(std::size_t offset, std::size_t size);"]
    generated = {}
    offset = 0
    packed_total = 0
    sample_total = 0
    for relative, namespace, group in (
        ("Infrastructure/ExternalServices/WavSamples", "WavSamples", "Instruments"),
        ("Presentation/Gameplay/Voices/VoiceSamples", "VoiceSamples", "Voices"),
    ):
        # 全配列を宣言順に読み、1つも間引かずカテゴリ別に連結する
        source = (ROOT / (relative + "Source.h")).read_text(encoding="utf-8-sig")
        arrays = re.findall(ARRAY, source, re.S)
        assert arrays and len(arrays) == len(re.findall(r"inline constexpr std::uint8_t", source))
        sample_total += len(arrays)
        data = bytearray()
        runtime = re.sub(ARRAY + r"\s*", "", source, flags=re.S)
        for name, body in arrays:
            assert not re.sub(r"0x[0-9A-Fa-f]{2}|[\s,]", "", body), name
            sample = bytes(int(value, 16) for value in re.findall(r"0x([0-9A-Fa-f]{2})", body))
            assert sample and f"sizeof({name})" in source, name
            header.append(f"inline constexpr Entry {name} {{ {offset + len(data)}, {len(sample)} }};")
            runtime = runtime.replace(f"sizeof({name})", f"Audio::PackedAudioSamples::{name}.size")
            runtime = re.sub(rf"\b{re.escape(name)}\s*,", f"Audio::PackedAudioSamples::{name}.offset,", runtime)
            data.extend(sample)
        packed = windows_codec(bytes(data), 2)
        assert windows_codec(packed, 2, True) == data
        header.extend([f"inline constexpr std::size_t {group}Size = {len(data)};",
                       "#ifdef FLOPPY_AUDIO_IMPLEMENTATION",
                       f"inline constexpr std::uint8_t {group}Data[] = {{"])
        header.extend("    " + ", ".join(f"0x{value:02X}" for value in packed[i:i+16]) + ","
                      for i in range(0, len(packed), 16))
        header.extend(["};", "#endif"])
        offset += len(data)
        packed_total += len(packed)

        # ランタイムはバイト列の代わりに一定のオフセットを保持する
        include = "PackedAudioSamples.h" if group == "Instruments" else "../../../Infrastructure/ExternalServices/PackedAudioSamples.h"
        runtime = runtime.replace("#pragma once", f'#pragma once\n// Generated by Scripts/PackAudioSamples.py; edit {namespace}Source.h\n#include "{include}"')
        runtime = runtime.replace("namespace " + namespace + "Source", "namespace " + namespace)
        runtime = runtime.replace("const std::uint8_t* data;", "std::size_t offset;")
        if group == "Instruments":
            runtime = runtime.replace("    if (!sample.data || sample.byteCount == 0 || sample.sampleCount == 0) return false;",
                "    // 追加の可逆圧縮を復元し、範囲と復元失敗を確認する\n"
                "    const auto* data = Audio::PackedAudioSamples::Get(sample.offset, sample.byteCount);\n"
                "    if (!data || sample.sampleCount == 0) return false;")
            runtime = runtime.replace("sample.data[", "data[")
        generated[relative + ".h"] = runtime
    header.extend([f"inline constexpr std::size_t TotalSize = {offset};", "} // namespace Audio::PackedAudioSamples", ""])
    generated["Infrastructure/ExternalServices/PackedAudioSamples.h"] = "\n".join(header)

    # 差分がある場合だけ書き込み、通常ビルドで不要な再コンパイルを避ける
    for relative, text in generated.items():
        path = ROOT / relative
        existing = path.read_text(encoding="utf-8-sig") if path.exists() else ""
        if args.check:
            if existing != text:
                raise SystemExit(f"Stale generated file: {relative}; run Scripts/PackAudioSamples.py")
        elif existing != text:
            path.write_text(text, encoding="utf-8", newline="\n")
    print(f"Audio: {offset} -> {packed_total} bytes, all {sample_total} samples retained, MSZIP lossless")


if __name__ == "__main__":
    main()
