<#
.SYNOPSIS
編集用MMLをWindows標準のLZMSで可逆圧縮し、埋め込みヘッダーを生成する
#>
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path $PSScriptRoot -Parent
$sourcePath = Join-Path $projectRoot 'Infrastructure/ExternalServices/MMLSource.h'
$outputPath = Join-Path $projectRoot 'Infrastructure/ExternalServices/PackedMMLData.h'

# Windows標準APIを使い、追加の圧縮ライブラリを不要にする
Add-Type -TypeDefinition @'
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
public static class MmlCompression {
    [DllImport("cabinet.dll", SetLastError = true)]
    public static extern bool CreateCompressor(uint algorithm, IntPtr allocator, out IntPtr handle);
    [DllImport("cabinet.dll", SetLastError = true)]
    public static extern bool Compress(IntPtr handle, byte[] input, UIntPtr inputSize,
        byte[] output, UIntPtr outputSize, out UIntPtr written);
    [DllImport("cabinet.dll")]
    public static extern bool CloseCompressor(IntPtr handle);
    /// <summary>入力バイト列をLZMS圧縮する</summary>
    /// <param name="input">元のMMLバイト列</param>
    /// <returns>圧縮データ</returns>
    public static byte[] Pack(byte[] input) {
        IntPtr handle;
        if (!CreateCompressor(5, IntPtr.Zero, out handle)) throw new Win32Exception();
        try {
            UIntPtr written;
            Compress(handle, input, (UIntPtr)input.Length, null, UIntPtr.Zero, out written);
            if (Marshal.GetLastWin32Error() != 122) throw new Win32Exception();
            byte[] output = new byte[checked((int)written.ToUInt64())];
            if (!Compress(handle, input, (UIntPtr)input.Length, output, (UIntPtr)output.Length, out written))
                throw new Win32Exception();
            Array.Resize(ref output, checked((int)written.ToUInt64()));
            return output;
        } finally { CloseCompressor(handle); }
    }
}
'@

# C++の文字列リテラルと同じ改行へ正規化し、全曲の反復をまとめて圧縮する
$source = [IO.File]::ReadAllText($sourcePath).Replace("`r", '')
$songs = [regex]::Matches($source, 'inline constexpr std::string_view (\w+) = R"MML\((.*?)\)MML";', 'Singleline')
if ($songs.Count -eq 0) { throw 'No original MML scores found' }
$bytes = [Collections.Generic.List[byte]]::new()
$entries = [Collections.Generic.List[string]]::new()
foreach ($song in $songs) {
    $data = [Text.Encoding]::UTF8.GetBytes($song.Groups[2].Value)
    $entries.Add(('    {{ "{0}", {1}, {2} }},' -f $song.Groups[1].Value, $bytes.Count, $data.Length))
    $bytes.AddRange($data)
}
$packed = [MmlCompression]::Pack($bytes.ToArray())
$lines = [Collections.Generic.List[string]]::new()
$lines.Add("#pragma once`n#include <cstddef>`n#include <cstdint>`n`n// Generated by Scripts/PackMml.ps1; edit MMLSource.h instead`nnamespace MMLData::Packed {")
$lines.Add("inline constexpr std::size_t OriginalSize = $($bytes.Count);")
$lines.Add('inline constexpr std::uint8_t Data[] = {')
for ($i = 0; $i -lt $packed.Length; $i += 16) {
    $last = [Math]::Min($i + 15, $packed.Length - 1)
    $lines.Add('    ' + (($packed[$i..$last] | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', ') + ',')
}
$lines.Add("};`nstruct Entry { const char* name; std::size_t offset; std::size_t size; };`ninline constexpr Entry Entries[] = {")
$lines.AddRange($entries)
$lines.Add("};`n} // namespace MMLData::Packed`n")
$result = $lines -join "`n"
$existing = if (Test-Path -LiteralPath $outputPath) { [IO.File]::ReadAllText($outputPath).Replace("`r`n", "`n") } else { '' }
if ($Check) {
    if ($existing -cne $result) { throw 'PackedMMLData.h is stale; run Scripts/PackMml.ps1' }
} elseif ($existing -cne $result) {
    [IO.File]::WriteAllText($outputPath, $result, [Text.UTF8Encoding]::new($false))
}
Write-Output "MML: $($bytes.Count) -> $($packed.Length) bytes ($($songs.Count) scores, lossless)"
