#pragma once
// Generated by Scripts/PackAudioSamples.py; edit VoiceSamplesSource.h
#include "../../../Infrastructure/ExternalServices/PackedAudioSamples.h"

#include <cstddef>
#include <cstdint>

namespace VoiceSamples {

struct ImaAdpcmSample {
    std::size_t offset;
    std::size_t byteCount;
    std::size_t sampleCount;
    std::uint32_t sampleRate;
    std::int16_t initialPredictor;
    std::uint8_t initialStepIndex;
};

inline constexpr ImaAdpcmSample tayamaDeath {
    Audio::PackedAudioSamples::tayamaDeathData.offset,
    Audio::PackedAudioSamples::tayamaDeathData.size,
    17366,
    6000,
    -478,
    0
};

inline constexpr ImaAdpcmSample eastsourceDeath {
    Audio::PackedAudioSamples::eastsourceDeathData.offset,
    Audio::PackedAudioSamples::eastsourceDeathData.size,
    16317,
    6000,
    -27,
    0
};

inline constexpr ImaAdpcmSample momijiDeath {
    Audio::PackedAudioSamples::momijiDeathData.offset,
    Audio::PackedAudioSamples::momijiDeathData.size,
    11775,
    6000,
    1093,
    0
};

inline constexpr ImaAdpcmSample mission {
    Audio::PackedAudioSamples::missionData.offset,
    Audio::PackedAudioSamples::missionData.size,
    3678,
    6000,
    267,
    0
};

inline constexpr ImaAdpcmSample start {
    Audio::PackedAudioSamples::startData.offset,
    Audio::PackedAudioSamples::startData.size,
    3147,
    6000,
    -187,
    0
};

inline constexpr ImaAdpcmSample arrested {
    Audio::PackedAudioSamples::arrestedData.offset,
    Audio::PackedAudioSamples::arrestedData.size,
    4962,
    6000,
    -1593,
    0
};

inline constexpr ImaAdpcmSample suspect {
    Audio::PackedAudioSamples::suspectData.offset,
    Audio::PackedAudioSamples::suspectData.size,
    4005,
    6000,
    -379,
    0
};

inline constexpr ImaAdpcmSample kotoDeath {
    Audio::PackedAudioSamples::kotoDeathData.offset,
    Audio::PackedAudioSamples::kotoDeathData.size,
    12012,
    6000,
    -5,
    0
};

inline constexpr ImaAdpcmSample ryotaDeath {
    Audio::PackedAudioSamples::ryotaDeathData.offset,
    Audio::PackedAudioSamples::ryotaDeathData.size,
    4032,
    6000,
    10535,
    0
};

inline constexpr ImaAdpcmSample lumiDeath {
    Audio::PackedAudioSamples::lumiDeathData.offset,
    Audio::PackedAudioSamples::lumiDeathData.size,
    13173,
    6000,
    -425,
    0
};

inline constexpr ImaAdpcmSample botamochiDeathBota {
    Audio::PackedAudioSamples::botamochiDeathBotaData.offset,
    Audio::PackedAudioSamples::botamochiDeathBotaData.size,
    9540,
    6000,
    0,
    0
};

inline constexpr ImaAdpcmSample botamochiDeathMochi {
    Audio::PackedAudioSamples::botamochiDeathMochiData.offset,
    Audio::PackedAudioSamples::botamochiDeathMochiData.size,
    9480,
    6000,
    -234,
    0
};

inline constexpr ImaAdpcmSample momijiDeathRattle2 {
    Audio::PackedAudioSamples::momijiDeathRattle2Data.offset,
    Audio::PackedAudioSamples::momijiDeathRattle2Data.size,
    9060,
    6000,
    0,
    0
};

inline constexpr ImaAdpcmSample momijiDeathRattle5 {
    Audio::PackedAudioSamples::momijiDeathRattle5Data.offset,
    Audio::PackedAudioSamples::momijiDeathRattle5Data.size,
    5124,
    6000,
    0,
    0
};

} // namespace VoiceSamples
