#pragma once
// Generated by Scripts/PackAudioSamples.py; edit WavSamplesSource.h
#include "PackedAudioSamples.h"

#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

namespace Audio {
namespace WavSamples {

struct WavData {
    const char* name;
    std::size_t offset;
    std::size_t byteCount;
    std::size_t sampleCount;
    int loopStart;
    int loopEnd;
    std::uint32_t checksum;
};

inline constexpr WavData SAMPLES[] = {
    { "AcousticGrandPiano", Audio::PackedAudioSamples::sample_AcousticGrandPiano.offset, Audio::PackedAudioSamples::sample_AcousticGrandPiano.size, 3004, 644, 2971, 0xACF56775u },
    { "Agogo", Audio::PackedAudioSamples::sample_Agogo.offset, Audio::PackedAudioSamples::sample_Agogo.size, 5320, -1, -1, 0xA4582F52u },
    { "BlownBottle", Audio::PackedAudioSamples::sample_BlownBottle.offset, Audio::PackedAudioSamples::sample_BlownBottle.size, 1651, 641, 1618, 0x3AE4C3CFu },
    { "BrassSection", Audio::PackedAudioSamples::sample_BrassSection.offset, Audio::PackedAudioSamples::sample_BrassSection.size, 2631, 642, 2598, 0xD75E3A74u },
    { "ChurchOrgan", Audio::PackedAudioSamples::sample_ChurchOrgan.offset, Audio::PackedAudioSamples::sample_ChurchOrgan.size, 1655, 640, 1622, 0x0A73CA94u },
    { "Clavi", Audio::PackedAudioSamples::sample_Clavi.offset, Audio::PackedAudioSamples::sample_Clavi.size, 1621, 641, 1588, 0x1A91769Bu },
    { "Crash", Audio::PackedAudioSamples::sample_Crash.offset, Audio::PackedAudioSamples::sample_Crash.size, 12000, -1, -1, 0xFE39C9F5u },
    { "DistortionGuitar", Audio::PackedAudioSamples::sample_DistortionGuitar.offset, Audio::PackedAudioSamples::sample_DistortionGuitar.size, 4618, 642, 4585, 0x7C4ED9F2u },
    { "DrawbarOrgan", Audio::PackedAudioSamples::sample_DrawbarOrgan.offset, Audio::PackedAudioSamples::sample_DrawbarOrgan.size, 2628, 639, 2595, 0x65371835u },
    { "Dulcimer", Audio::PackedAudioSamples::sample_Dulcimer.offset, Audio::PackedAudioSamples::sample_Dulcimer.size, 2049, 642, 2016, 0xFA301CB4u },
    { "ElectricPiano1", Audio::PackedAudioSamples::sample_ElectricPiano1.offset, Audio::PackedAudioSamples::sample_ElectricPiano1.size, 763, 668, 730, 0xA25CAEBDu },
    { "FrenchHorn", Audio::PackedAudioSamples::sample_FrenchHorn.offset, Audio::PackedAudioSamples::sample_FrenchHorn.size, 1985, 651, 1952, 0x888595BFu },
    { "GuitarFretNoise", Audio::PackedAudioSamples::sample_GuitarFretNoise.offset, Audio::PackedAudioSamples::sample_GuitarFretNoise.size, 1600, -1, -1, 0x39F3AA41u },
    { "Harpsichord", Audio::PackedAudioSamples::sample_Harpsichord.offset, Audio::PackedAudioSamples::sample_Harpsichord.size, 2111, 642, 2078, 0xDF8815F5u },
    { "HiHatOpen", Audio::PackedAudioSamples::sample_HiHatOpen.offset, Audio::PackedAudioSamples::sample_HiHatOpen.size, 4000, -1, -1, 0xC02BACD5u },
    { "Kick", Audio::PackedAudioSamples::sample_Kick.offset, Audio::PackedAudioSamples::sample_Kick.size, 4000, -1, -1, 0x6CC9ADA5u },
    { "LeadCalliope", Audio::PackedAudioSamples::sample_LeadCalliope.offset, Audio::PackedAudioSamples::sample_LeadCalliope.size, 2631, 642, 2598, 0x3C2991DBu },
    { "LeadCharang", Audio::PackedAudioSamples::sample_LeadCharang.offset, Audio::PackedAudioSamples::sample_LeadCharang.size, 3640, 642, 3607, 0x8817877Bu },
    { "LeadFifths", Audio::PackedAudioSamples::sample_LeadFifths.offset, Audio::PackedAudioSamples::sample_LeadFifths.size, 4649, 642, 4616, 0xF6A8ABB3u },
    { "LeadSawtooth", Audio::PackedAudioSamples::sample_LeadSawtooth.offset, Audio::PackedAudioSamples::sample_LeadSawtooth.size, 3640, 642, 3607, 0x58FB1729u },
    { "LeadSquare", Audio::PackedAudioSamples::sample_LeadSquare.offset, Audio::PackedAudioSamples::sample_LeadSquare.size, 3609, 642, 3576, 0xB6D12FF8u },
    { "MelodicTom", Audio::PackedAudioSamples::sample_MelodicTom.offset, Audio::PackedAudioSamples::sample_MelodicTom.size, 6400, -1, -1, 0xC88A1561u },
    { "MusicBox", Audio::PackedAudioSamples::sample_MusicBox.offset, Audio::PackedAudioSamples::sample_MusicBox.size, 1255, 642, 1222, 0xE1AC82D1u },
    { "NylonAcousticGuitar", Audio::PackedAudioSamples::sample_NylonAcousticGuitar.offset, Audio::PackedAudioSamples::sample_NylonAcousticGuitar.size, 2111, 642, 2078, 0xB3ABACA0u },
    { "Ocarina", Audio::PackedAudioSamples::sample_Ocarina.offset, Audio::PackedAudioSamples::sample_Ocarina.size, 5627, 641, 5594, 0xB3931444u },
    { "OverdrivenGuitar", Audio::PackedAudioSamples::sample_OverdrivenGuitar.offset, Audio::PackedAudioSamples::sample_OverdrivenGuitar.size, 4618, 642, 4585, 0x33C575EDu },
    { "RockOrgan", Audio::PackedAudioSamples::sample_RockOrgan.offset, Audio::PackedAudioSamples::sample_RockOrgan.size, 2631, 642, 2598, 0x6C86D62Cu },
    { "Snare", Audio::PackedAudioSamples::sample_Snare.offset, Audio::PackedAudioSamples::sample_Snare.size, 2400, -1, -1, 0x2CE4ED89u },
    { "StringEnsemble1", Audio::PackedAudioSamples::sample_StringEnsemble1.offset, Audio::PackedAudioSamples::sample_StringEnsemble1.size, 1744, 642, 1711, 0x9ABB91E6u },
    { "SynthDrum", Audio::PackedAudioSamples::sample_SynthDrum.offset, Audio::PackedAudioSamples::sample_SynthDrum.size, 3200, -1, -1, 0x23F32C49u },
    { "Tambourine", Audio::PackedAudioSamples::sample_Tambourine.offset, Audio::PackedAudioSamples::sample_Tambourine.size, 3200, -1, -1, 0x66550F3Du },
    { "TomHigh", Audio::PackedAudioSamples::sample_TomHigh.offset, Audio::PackedAudioSamples::sample_TomHigh.size, 2400, -1, -1, 0xED80ED0Du },
    { "TomLow", Audio::PackedAudioSamples::sample_TomLow.offset, Audio::PackedAudioSamples::sample_TomLow.size, 3200, -1, -1, 0x0A0C1AC1u },
    { "TomMid", Audio::PackedAudioSamples::sample_TomMid.offset, Audio::PackedAudioSamples::sample_TomMid.size, 2800, -1, -1, 0x7B6E6695u },
    { "Trumpet", Audio::PackedAudioSamples::sample_Trumpet.offset, Audio::PackedAudioSamples::sample_Trumpet.size, 1676, 641, 1643, 0x400B98C1u },
    { "Woodblock", Audio::PackedAudioSamples::sample_Woodblock.offset, Audio::PackedAudioSamples::sample_Woodblock.size, 1600, -1, -1, 0xB935E231u },
    { "ChoirAahs", Audio::PackedAudioSamples::sample_ChoirAahs.offset, Audio::PackedAudioSamples::sample_ChoirAahs.size, 1681, 640, 1648, 0xDA8197E4u },
    { "Oboe", Audio::PackedAudioSamples::sample_Oboe.offset, Audio::PackedAudioSamples::sample_Oboe.size, 1291, 640, 1258, 0x8C44F243u },
    { "SynthBass1", Audio::PackedAudioSamples::sample_SynthBass1.offset, Audio::PackedAudioSamples::sample_SynthBass1.size, 1255, 611, 1222, 0x8B2F5698u },
    { "Vibraphone", Audio::PackedAudioSamples::sample_Vibraphone.offset, Audio::PackedAudioSamples::sample_Vibraphone.size, 4435, 642, 4402, 0xA8E04434u },
};

/**
 * @brief 名前から圧縮PCMサンプルを取得する
 * @param name サンプル名
 * @return 該当サンプル、存在しない場合nullptr
 */
inline const WavData* Find(std::string_view name) {
    for (const auto& item : SAMPLES) {
        if (name == item.name) return &item;
    }
    return nullptr;
}

/**
 * @brief 差分圧縮された8bit PCMを復号する
 * @param sample 圧縮PCMサンプル
 * @param output 復号先
 * @return 復号に成功した場合true
 */
inline bool Decode(const WavData& sample, std::vector<std::uint8_t>& output) {
    // 追加の可逆圧縮を復元し、範囲と復元失敗を確認する
    const auto* data = Audio::PackedAudioSamples::Get(sample.offset, sample.byteCount);
    if (!data || sample.sampleCount == 0) return false;

    // 先頭値を基準に4bit差分を順次復号する
    output.resize(sample.sampleCount);
    output[0] = data[0];
    std::size_t bitOffset = 0;
    const auto ReadBits = [&](unsigned count, std::uint32_t& value) {
        if (bitOffset + count > (sample.byteCount - 1) * 8) return false;
        value = 0;
        for (unsigned bit = 0; bit < count; ++bit) {
            const std::size_t sourceBit = bitOffset + bit;
            value |= ((data[1 + sourceBit / 8] >> (sourceBit % 8)) & 1u) << bit;
        }
        bitOffset += count;
        return true;
    };

    for (std::size_t i = 1; i < sample.sampleCount; ++i) {
        std::uint32_t code = 0;
        if (!ReadBits(4, code)) return false;
        if (code == 15) {
            if (!ReadBits(8, code)) return false;
            output[i] = static_cast<std::uint8_t>(code);
            continue;
        }
        const int value = static_cast<int>(output[i - 1]) + (static_cast<int>(code) - 7) * 4;
        if (value < 0 || value > 255) return false;
        output[i] = static_cast<std::uint8_t>(value);
    }
    return true;
}

} // namespace WavSamples
} // namespace Audio
